### ISSUE TITLE
Подготовка выборки лиц мужчин с бородой

### ISSUE THREAD

**Issue by markpolyak** [markpolyak/faces-dataset#1]
# Задание
1. Ознакомиться с требованиями к фотографиям лиц: [image_specification.pdf](https://github.com/markpolyak/faces-dataset/blob/main/image_specification.pdf)
2. Создать отдельную ветку в репозитории.
3. Найти и загрузить в папку [beard](https://github.com/markpolyak/faces-dataset/tree/main/beard) в новой ветке 100 изображений: 50 мужских лиц с бородой, 50 мужских лиц без бороды.
4. Внести относительные ссылки на изображения и информацию о них в файл `README.md` в этой папке.
5. Подготовить пул-реквест в ветку `main`.

**Comment by MarTopr** [comment]
Топорищева М. 4933
