### ISSUE TITLE
Подготовка выборки лиц в очках и без очков

### ISSUE THREAD

**Issue by markpolyak** [markpolyak/faces-dataset#2]
# Задание
1. Ознакомиться с требованиями к фотографиям лиц: [image_specification.pdf](https://github.com/markpolyak/faces-dataset/blob/main/image_specification.pdf)
2. Создать отдельную ветку в репозитории.
3. Найти и загрузить в папку [glasses](https://github.com/markpolyak/faces-dataset/tree/main/glasses) в новой ветке 100 изображений: 50 лиц в очках, 50 лиц без очков. Распределение по полу и возрасту - равномерное.
4. Внести относительные ссылки на изображения и информацию о них в файл `README.md` в этой папке.
5. Подготовить пул-реквест в ветку `main`.

**Comment by wolk2608** [comment]
Черкасов, 4936
