### ISSUE TITLE
Подготовка выборки лиц: рок-музыканты

### ISSUE THREAD

**Issue by markpolyak** [markpolyak/faces-dataset#4]
# Задание
1. Ознакомиться с требованиями к фотографиям лиц: [image_specification.pdf](https://github.com/markpolyak/faces-dataset/blob/main/image_specification.pdf)
2. Создать отдельную ветку в репозитории.
3. Найти и загрузить в папку [rock](https://github.com/markpolyak/faces-dataset/tree/main/rock) в новой ветке 100 изображений лиц рок музыкантов. Распределение по полу и возрасту - равномерное.
4. Внести относительные ссылки на изображения и информацию о них в файл `README.md` в этой папке.
5. Подготовить пул-реквест в ветку `main`.

**Comment by Zefiry** [comment]
Судак Алёна, группа 4936
